/**
 * Template Factory - Sistema de recetas
 * PASS C - generator-v1 + TF-F3-RECIPE-DIVERSITY
 */

import type { ActionRole, IndustryId } from "./industries";
import type { ButtonPresetId, ThemeId } from "./registries";
import { BTN_RADII, PROFILE_RADII } from "./registries";

export type BtnRadiusValue = (typeof BTN_RADII)[number];
export type ProfileRadiusValue = (typeof PROFILE_RADII)[number];

export interface Recipe {
  id: string;
  label: string;
  industry: IndustryId;
  themes: readonly ThemeId[];
  buttonPresets: readonly ButtonPresetId[];
  ctaPriority: readonly ActionRole[];
  profileRadii: readonly ProfileRadiusValue[];
  btnRadii: readonly BtnRadiusValue[];
  gridCols: readonly (1 | 2)[];
  socialRange: readonly [number, number];
  bannerProbability: number;
  style: string;
}

export const RECIPES: Record<string, Recipe> = {
  medical_compact: {
    id: "medical_compact",
    label: "Compact Minimal",
    industry: "medical",
    themes: ["premium-white","emerald-luxury","clinical-trust"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  medical_editorial: {
    id: "medical_editorial",
    label: "Editorial Split",
    industry: "medical",
    themes: ["premium-white","emerald-luxury","clinical-trust"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  medical_trust: {
    id: "medical_trust",
    label: "Professional Trust",
    industry: "medical",
    themes: ["premium-white","emerald-luxury","clinical-trust"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  legal_trust: {
    id: "legal_trust",
    label: "Professional Trust",
    industry: "legal",
    themes: ["black-gold","executive-blue","graphite"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  legal_editorial: {
    id: "legal_editorial",
    label: "Editorial Split",
    industry: "legal",
    themes: ["black-gold","executive-blue","graphite"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  legal_bento: {
    id: "legal_bento",
    label: "Bento Layout",
    industry: "legal",
    themes: ["black-gold","executive-blue","graphite"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  restaurant_trust: {
    id: "restaurant_trust",
    label: "Professional Trust",
    industry: "restaurant",
    themes: ["burgundy-elegant","black-gold","ivory-gold","warm"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  restaurant_editorial: {
    id: "restaurant_editorial",
    label: "Editorial Split",
    industry: "restaurant",
    themes: ["burgundy-elegant","black-gold","ivory-gold","warm"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  restaurant_compact: {
    id: "restaurant_compact",
    label: "Compact Minimal",
    industry: "restaurant",
    themes: ["burgundy-elegant","black-gold","ivory-gold","warm"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  barber_bento: {
    id: "barber_bento",
    label: "Bento Layout",
    industry: "barber",
    themes: ["graphite","black-silver","black-gold"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  barber_compact: {
    id: "barber_compact",
    label: "Compact Minimal",
    industry: "barber",
    themes: ["graphite","black-silver","black-gold"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  barber_creator: {
    id: "barber_creator",
    label: "Creator Spotlight",
    industry: "barber",
    themes: ["graphite","black-silver","black-gold"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  dental_editorial: {
    id: "dental_editorial",
    label: "Editorial Split",
    industry: "dental",
    themes: ["premium-white","clinical-trust","emerald-luxury"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  dental_trust: {
    id: "dental_trust",
    label: "Professional Trust",
    industry: "dental",
    themes: ["premium-white","clinical-trust","emerald-luxury"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  dental_creator: {
    id: "dental_creator",
    label: "Creator Spotlight",
    industry: "dental",
    themes: ["premium-white","clinical-trust","emerald-luxury"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  veterinary_editorial: {
    id: "veterinary_editorial",
    label: "Editorial Split",
    industry: "veterinary",
    themes: ["premium-white","emerald-luxury","warm"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  veterinary_compact: {
    id: "veterinary_compact",
    label: "Compact Minimal",
    industry: "veterinary",
    themes: ["premium-white","emerald-luxury","warm"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  veterinary_creator: {
    id: "veterinary_creator",
    label: "Creator Spotlight",
    industry: "veterinary",
    themes: ["premium-white","emerald-luxury","warm"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  beauty_compact: {
    id: "beauty_compact",
    label: "Compact Minimal",
    industry: "beauty",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  beauty_trust: {
    id: "beauty_trust",
    label: "Professional Trust",
    industry: "beauty",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  beauty_editorial: {
    id: "beauty_editorial",
    label: "Editorial Split",
    industry: "beauty",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  spa_compact: {
    id: "spa_compact",
    label: "Compact Minimal",
    industry: "spa",
    themes: ["ivory-gold","emerald-luxury","warm"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  spa_trust: {
    id: "spa_trust",
    label: "Professional Trust",
    industry: "spa",
    themes: ["ivory-gold","emerald-luxury","warm"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  spa_bento: {
    id: "spa_bento",
    label: "Bento Layout",
    industry: "spa",
    themes: ["ivory-gold","emerald-luxury","warm"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  hair_salon_editorial: {
    id: "hair_salon_editorial",
    label: "Editorial Split",
    industry: "hair_salon",
    themes: ["black-silver","rose-gold","bold"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  hair_salon_trust: {
    id: "hair_salon_trust",
    label: "Professional Trust",
    industry: "hair_salon",
    themes: ["black-silver","rose-gold","bold"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  hair_salon_compact: {
    id: "hair_salon_compact",
    label: "Compact Minimal",
    industry: "hair_salon",
    themes: ["black-silver","rose-gold","bold"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  tattoo_editorial: {
    id: "tattoo_editorial",
    label: "Editorial Split",
    industry: "tattoo",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  tattoo_trust: {
    id: "tattoo_trust",
    label: "Professional Trust",
    industry: "tattoo",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  tattoo_compact: {
    id: "tattoo_compact",
    label: "Compact Minimal",
    industry: "tattoo",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  fitness_creator: {
    id: "fitness_creator",
    label: "Creator Spotlight",
    industry: "fitness",
    themes: ["graphite","executive-blue","athletic"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  fitness_trust: {
    id: "fitness_trust",
    label: "Professional Trust",
    industry: "fitness",
    themes: ["graphite","executive-blue","athletic"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  fitness_bento: {
    id: "fitness_bento",
    label: "Bento Layout",
    industry: "fitness",
    themes: ["graphite","executive-blue","athletic"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  coach_compact: {
    id: "coach_compact",
    label: "Compact Minimal",
    industry: "coach",
    themes: ["executive-blue","premium-white","light"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  coach_editorial: {
    id: "coach_editorial",
    label: "Editorial Split",
    industry: "coach",
    themes: ["executive-blue","premium-white","light"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  coach_bento: {
    id: "coach_bento",
    label: "Bento Layout",
    industry: "coach",
    themes: ["executive-blue","premium-white","light"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  consultant_trust: {
    id: "consultant_trust",
    label: "Professional Trust",
    industry: "consultant",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  consultant_editorial: {
    id: "consultant_editorial",
    label: "Editorial Split",
    industry: "consultant",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  consultant_creator: {
    id: "consultant_creator",
    label: "Creator Spotlight",
    industry: "consultant",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  real_estate_compact: {
    id: "real_estate_compact",
    label: "Compact Minimal",
    industry: "real_estate",
    themes: ["executive-blue","ivory-gold","luxury"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  real_estate_creator: {
    id: "real_estate_creator",
    label: "Creator Spotlight",
    industry: "real_estate",
    themes: ["executive-blue","ivory-gold","luxury"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  real_estate_editorial: {
    id: "real_estate_editorial",
    label: "Editorial Split",
    industry: "real_estate",
    themes: ["executive-blue","ivory-gold","luxury"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  architect_trust: {
    id: "architect_trust",
    label: "Professional Trust",
    industry: "architect",
    themes: ["graphite","premium-white","minimal"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  architect_editorial: {
    id: "architect_editorial",
    label: "Editorial Split",
    industry: "architect",
    themes: ["graphite","premium-white","minimal"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  architect_compact: {
    id: "architect_compact",
    label: "Compact Minimal",
    industry: "architect",
    themes: ["graphite","premium-white","minimal"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  photographer_trust: {
    id: "photographer_trust",
    label: "Professional Trust",
    industry: "photographer",
    themes: ["black-gold","premium-white","editorial"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  photographer_editorial: {
    id: "photographer_editorial",
    label: "Editorial Split",
    industry: "photographer",
    themes: ["black-gold","premium-white","editorial"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  photographer_compact: {
    id: "photographer_compact",
    label: "Compact Minimal",
    industry: "photographer",
    themes: ["black-gold","premium-white","editorial"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  creator_trust: {
    id: "creator_trust",
    label: "Professional Trust",
    industry: "creator",
    themes: ["rose-gold","executive-blue","vibrant"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  creator_editorial: {
    id: "creator_editorial",
    label: "Editorial Split",
    industry: "creator",
    themes: ["rose-gold","executive-blue","vibrant"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  creator_compact: {
    id: "creator_compact",
    label: "Compact Minimal",
    industry: "creator",
    themes: ["rose-gold","executive-blue","vibrant"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  influencer_compact: {
    id: "influencer_compact",
    label: "Compact Minimal",
    industry: "influencer",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  influencer_editorial: {
    id: "influencer_editorial",
    label: "Editorial Split",
    industry: "influencer",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  influencer_creator: {
    id: "influencer_creator",
    label: "Creator Spotlight",
    industry: "influencer",
    themes: ["rose-gold","premium-white","luxury"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  musician_creator: {
    id: "musician_creator",
    label: "Creator Spotlight",
    industry: "musician",
    themes: ["graphite","burgundy-elegant","dark"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  musician_trust: {
    id: "musician_trust",
    label: "Professional Trust",
    industry: "musician",
    themes: ["graphite","burgundy-elegant","dark"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  musician_editorial: {
    id: "musician_editorial",
    label: "Editorial Split",
    industry: "musician",
    themes: ["graphite","burgundy-elegant","dark"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  dj_compact: {
    id: "dj_compact",
    label: "Compact Minimal",
    industry: "dj",
    themes: ["black-gold","executive-blue","entertainment"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  dj_bento: {
    id: "dj_bento",
    label: "Bento Layout",
    industry: "dj",
    themes: ["black-gold","executive-blue","entertainment"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  dj_trust: {
    id: "dj_trust",
    label: "Professional Trust",
    industry: "dj",
    themes: ["black-gold","executive-blue","entertainment"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  streamer_compact: {
    id: "streamer_compact",
    label: "Compact Minimal",
    industry: "streamer",
    themes: ["executive-blue","graphite","gaming_entertainment"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  streamer_trust: {
    id: "streamer_trust",
    label: "Professional Trust",
    industry: "streamer",
    themes: ["executive-blue","graphite","gaming_entertainment"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  streamer_bento: {
    id: "streamer_bento",
    label: "Bento Layout",
    industry: "streamer",
    themes: ["executive-blue","graphite","gaming_entertainment"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  hotel_editorial: {
    id: "hotel_editorial",
    label: "Editorial Split",
    industry: "hotel",
    themes: ["ivory-gold","premium-white","hospitality"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  hotel_trust: {
    id: "hotel_trust",
    label: "Professional Trust",
    industry: "hotel",
    themes: ["ivory-gold","premium-white","hospitality"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  hotel_compact: {
    id: "hotel_compact",
    label: "Compact Minimal",
    industry: "hotel",
    themes: ["ivory-gold","premium-white","hospitality"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  cafe_compact: {
    id: "cafe_compact",
    label: "Compact Minimal",
    industry: "cafe",
    themes: ["burgundy-elegant","ivory-gold","warm"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  cafe_creator: {
    id: "cafe_creator",
    label: "Creator Spotlight",
    industry: "cafe",
    themes: ["burgundy-elegant","ivory-gold","warm"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  cafe_trust: {
    id: "cafe_trust",
    label: "Professional Trust",
    industry: "cafe",
    themes: ["burgundy-elegant","ivory-gold","warm"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  nightlife_creator: {
    id: "nightlife_creator",
    label: "Creator Spotlight",
    industry: "nightlife",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  nightlife_bento: {
    id: "nightlife_bento",
    label: "Bento Layout",
    industry: "nightlife",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  nightlife_editorial: {
    id: "nightlife_editorial",
    label: "Editorial Split",
    industry: "nightlife",
    themes: ["black-gold","graphite","dark"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  jewelry_editorial: {
    id: "jewelry_editorial",
    label: "Editorial Split",
    industry: "jewelry",
    themes: ["rose-gold","black-gold","luxury"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  jewelry_compact: {
    id: "jewelry_compact",
    label: "Compact Minimal",
    industry: "jewelry",
    themes: ["rose-gold","black-gold","luxury"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  jewelry_trust: {
    id: "jewelry_trust",
    label: "Professional Trust",
    industry: "jewelry",
    themes: ["rose-gold","black-gold","luxury"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  automotive_editorial: {
    id: "automotive_editorial",
    label: "Editorial Split",
    industry: "automotive",
    themes: ["graphite","executive-blue","dark"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  automotive_compact: {
    id: "automotive_compact",
    label: "Compact Minimal",
    industry: "automotive",
    themes: ["graphite","executive-blue","dark"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  automotive_trust: {
    id: "automotive_trust",
    label: "Professional Trust",
    industry: "automotive",
    themes: ["graphite","executive-blue","dark"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  education_editorial: {
    id: "education_editorial",
    label: "Editorial Split",
    industry: "education",
    themes: ["executive-blue","premium-white","professional"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  education_compact: {
    id: "education_compact",
    label: "Compact Minimal",
    industry: "education",
    themes: ["executive-blue","premium-white","professional"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  education_trust: {
    id: "education_trust",
    label: "Professional Trust",
    industry: "education",
    themes: ["executive-blue","premium-white","professional"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  events_editorial: {
    id: "events_editorial",
    label: "Editorial Split",
    industry: "events",
    themes: ["rose-gold","ivory-gold","hospitality"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  events_compact: {
    id: "events_compact",
    label: "Compact Minimal",
    industry: "events",
    themes: ["rose-gold","ivory-gold","hospitality"] as any,
    buttonPresets: ["solid","outline"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["16px","9999px"] as any,
    gridCols: [1] as any,
    socialRange: [1,2] as any,
    bannerProbability: 0,
    style: "compact",
  },
  events_bento: {
    id: "events_bento",
    label: "Bento Layout",
    industry: "events",
    themes: ["rose-gold","ivory-gold","hospitality"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  ecommerce_creator_editorial: {
    id: "ecommerce_creator_editorial",
    label: "Editorial Split",
    industry: "ecommerce_creator",
    themes: ["premium-white","black-gold","universal"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  ecommerce_creator_trust: {
    id: "ecommerce_creator_trust",
    label: "Professional Trust",
    industry: "ecommerce_creator",
    themes: ["premium-white","black-gold","universal"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
  ecommerce_creator_creator: {
    id: "ecommerce_creator_creator",
    label: "Creator Spotlight",
    industry: "ecommerce_creator",
    themes: ["premium-white","black-gold","universal"] as any,
    buttonPresets: ["glass","solid"] as any,
    ctaPriority: ["primary","social","info","contact","location"] as any,
    profileRadii: ["50%","24px"] as any,
    btnRadii: ["9999px","16px"] as any,
    gridCols: [1,2] as any,
    socialRange: [4,5] as any,
    bannerProbability: 0.8,
    style: "creator",
  },
  professional_services_editorial: {
    id: "professional_services_editorial",
    label: "Editorial Split",
    industry: "professional_services",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["outline","minimal"] as any,
    ctaPriority: ["primary","contact","info","location","social"] as any,
    profileRadii: ["0px","50%"] as any,
    btnRadii: ["0px","16px"] as any,
    gridCols: [1] as any,
    socialRange: [1,3] as any,
    bannerProbability: 1,
    style: "editorial",
  },
  professional_services_bento: {
    id: "professional_services_bento",
    label: "Bento Layout",
    industry: "professional_services",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["soft","glass","solid"] as any,
    ctaPriority: ["primary","info","contact","social","location"] as any,
    profileRadii: ["24px","16px"] as any,
    btnRadii: ["16px"] as any,
    gridCols: [2] as any,
    socialRange: [3,5] as any,
    bannerProbability: 0.1,
    style: "bento",
  },
  professional_services_trust: {
    id: "professional_services_trust",
    label: "Professional Trust",
    industry: "professional_services",
    themes: ["graphite","executive-blue","professional"] as any,
    buttonPresets: ["solid","premium"] as any,
    ctaPriority: ["primary","location","contact","info","social"] as any,
    profileRadii: ["50%"] as any,
    btnRadii: ["9999px"] as any,
    gridCols: [1] as any,
    socialRange: [2,4] as any,
    bannerProbability: 0.5,
    style: "trust",
  },
};

export const RECIPE_IDS = Object.keys(RECIPES);

export function getRecipesForIndustry(industry: IndustryId): Recipe[] {
  return Object.values(RECIPES).filter((recipe) => recipe.industry === industry);
}

export function getRecipe(recipeId: string): Recipe {
  const recipe = RECIPES[recipeId];
  if (!recipe) throw new Error(`Receta desconocida: ${recipeId}`);
  return recipe;
}

export function getDefaultRecipe(industry: IndustryId): Recipe {
  const candidates = getRecipesForIndustry(industry);
  if (candidates.length === 0) {
    throw new Error(`La industria ${industry} no tiene recetas registradas`);
  }
  return candidates[0]!;
}
