/**
 * PREMIUM TEMPLATE STUDIO — public module surface.
 *
 * Editor:   <PremiumTemplateStudio config adapters onSave onPublish />
 * Renderer: <PublicTemplateRenderer config />   (no editor code required)
 *
 * Everything else is data: BioTemplateConfig is JSON, so it can be stored,
 * versioned, duplicated, or generated by an AI without touching React.
 */

export { PremiumTemplateStudio } from "./components/PremiumTemplateStudio";
export type { PremiumTemplateStudioProps } from "./components/PremiumTemplateStudio";
export { PublicTemplateRenderer } from "./engine/PublicTemplateRenderer";
export type { PublicTemplateRendererProps } from "./engine/PublicTemplateRenderer";
export { TemplateRenderer } from "./engine/TemplateRenderer";

export { createTemplate, applyTemplateDefinition } from "./engine/TemplateFactory";
export { buildTemplate, mergeConfig, duplicateTemplate } from "./engine/TemplateBuilder";
export { validateTemplate, parseTemplateJson, migrateConfig } from "./engine/TemplateValidator";
export { BlockRegistry, registerBlock, getBlockComponent } from "./engine/BlockRegistry";

export {
  TEMPLATE_DEFINITIONS,
  getTemplateDefinition,
  createDemoConfig,
} from "./templates/definitions";
export { THEMES, getTheme, TYPOGRAPHY_PRESETS } from "./constants/themes";
export { LAYOUTS, getLayout } from "./constants/layouts";
export { BLOCK_DEFINITIONS, createBlock } from "./constants/blockDefinitions";

export { defaultAdapters, resolveAdapters, localStorageAdapter } from "./adapters";
export type {
  StudioAdapters,
  StorageAdapter,
  AssetAdapter,
  AnalyticsAdapter,
  AuthAdapter,
} from "./adapters";

export * from "./types";
