import type { CSSProperties } from "react";
import type { Breakpoint, PageBlock, PageConfig } from "../lib/editorCandidateModel";
import { normalizeRichCard, type CardTextStyle } from "../lib/richCards";
import "./premium-cards.css";

function textStyle(style: CardTextStyle | undefined, fallback: string): CSSProperties {
  const current = style ?? {};
  const stroke = Number(current.textStrokeWidth ?? 0);
  return { color: current.color ?? fallback, fontFamily: current.fontFamily, fontSize: current.fontSize ? `${current.fontSize}px` : undefined, fontWeight: current.fontWeight, fontStyle: current.italic ? "italic" : undefined, letterSpacing: current.letterSpacing === undefined ? undefined : `${current.letterSpacing}px`, lineHeight: current.lineHeight, textAlign: current.textAlign, WebkitTextStroke: stroke > 0 ? `${stroke}px ${current.textStrokeColor ?? "#000000"}` : undefined };
}

export function PremiumCardsBlock({ block, page, breakpoint, visual, shared, onSelect, preview, onPreviewDestination }: { block: PageBlock; page: PageConfig; breakpoint: Breakpoint; visual: CSSProperties; shared: string; onSelect: (id: string) => void; preview: boolean; onPreviewDestination: (value?: string) => void }) {
  const items = ((block.props["items"] as Array<ReturnType<typeof normalizeRichCard>> | undefined) ?? []).map(item => normalizeRichCard(item));
  const responsive = ((block.props["style"] as { responsive?: Partial<Record<Breakpoint, { columns?: number }>> } | undefined)?.responsive?.[breakpoint]?.columns);
  const columns = Number(responsive ?? block.props["layout"] ?? 1);
  const selectBlock = () => onSelect(block.id);
  const keySelect = (event: React.KeyboardEvent<HTMLDivElement>) => { if (!preview && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); selectBlock(); } };
  return <div data-block-id={block.id} className={`ep-card-block ep-premium-card-block ${shared} ${columns === 2 ? "is-two-column" : ""}`} style={{ ...visual, background: String(block.props["background"] ?? ""), color: String(block.props["color"] ?? ""), "--ep-columns": columns } as CSSProperties} role={preview ? undefined : "button"} tabIndex={preview ? undefined : 0} onKeyDown={keySelect} onClick={selectBlock}>{items.map(item => { const hasImage = Boolean(item.imageEnabled && item.imageUrl); const cardDestination = item.cardLinkEnabled ? item.cardUrl : ""; const ctaAlign = item.ctaStyle?.textAlign ?? "left"; const ctaJustify = ctaAlign === "right" ? "end" : ctaAlign === "center" ? "center" : "start"; const navigateCard = (event: React.MouseEvent<HTMLSpanElement>) => { event.stopPropagation(); if (preview && cardDestination) onPreviewDestination(cardDestination); else if (!preview) selectBlock(); }; const navigateCta = (event: React.MouseEvent<HTMLButtonElement>) => { event.stopPropagation(); if (preview && item.ctaUrl) onPreviewDestination(item.ctaUrl); else if (!preview) selectBlock(); }; return <span className={`ep-rich-card ${hasImage ? "has-image" : ""} image-${item.imageSide} ${preview && cardDestination ? "is-clickable" : ""}`} key={item.id} role={preview && cardDestination ? "link" : undefined} tabIndex={preview && cardDestination ? 0 : undefined} onKeyDown={event => { if (preview && cardDestination && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); onPreviewDestination(cardDestination); } }} onClick={navigateCard} style={{ background: item.background, borderColor: item.borderColor, borderStyle: Number(item.borderWidth) > 0 ? "solid" : "none", borderWidth: item.borderWidth, borderRadius: item.radius, boxShadow: item.shadow ? `0 8px ${item.shadow}px rgba(0,0,0,.28)` : undefined, padding: item.padding }}><span className="ep-rich-card-copy"><b style={textStyle(item.titleStyle, "#f1eee8")}>{item.title}</b><small style={textStyle(item.descriptionStyle, "#aeb4bd")}>{item.description}</small>{item.ctaEnabled !== false && item.cta && <button type="button" className="ep-rich-card-cta" style={{ ...textStyle(item.ctaStyle, "#e8c38e"), justifySelf: ctaJustify }} onClick={navigateCta}>{item.cta} →</button>}</span>{hasImage && <span className="ep-rich-card-image" style={{ backgroundImage: `url(${item.imageUrl})` }} aria-label="Imagen de tarjeta" />}</span>; })}</div>;
}
