/**
 * CRIPQER — PRODUCT ASSET ENTITLEMENT MANIFEST V1
 *
 * Maps REAL Power Editor assets to product classifications (STANDARD | PREMIUM)
 * so the Product Capability Policy Core can gate *new* selection/insertion/
 * application. It is pure, declarative product metadata.
 *
 * Responsibilities:
 *   - Classify every currently implemented block, layout, section preset and
 *     template into STANDARD or PREMIUM, exactly once.
 *   - Map each classification to the capability that authorizes NEW insertion:
 *       standard  → standard_blocks / standard_sections / standard_templates /
 *                   basic_layout_selection
 *       premium   → premium_blocks / premium_sections / premium_templates /
 *                   advanced_layout
 *   - Fail closed: an unknown/unclassified asset is `UNKNOWN`, never silently
 *     treated as STANDARD (Free).
 *
 * This manifest does NOT:
 *   - implement UI locks
 *   - modify the Power Editor, renderer, or Billing
 *   - change BioTemplateConfig or renderer behavior
 *   - control RENDERING or STORAGE preservation
 *
 * ASSET ENTITLEMENT CONTROLS SELECTION/INSERTION/APPLICATION, NOT RENDERING.
 * A Free user may still render and preserve a premium asset already present in
 * a canonical config (e.g. generated by Engine V2); they merely cannot newly
 * add/select/apply it.
 *
 * Boundary: the frozen Product Capability Policy Core
 * (`src/lib/product-entitlements/capabilities.ts`) is READ ONLY. This manifest
 * imports only its `ProductCapability` *type* (erased at compile time) so the
 * required capability ids are guaranteed valid without runtime coupling.
 */

import type { ProductCapability } from "./capabilities.ts";

/* ============================================================================
 * 1. CORE TYPES
 * ========================================================================== */

/** Product classification of an asset. */
export type ProductAssetTier = "standard" | "premium";

/** The kind of asset being classified. */
export type ProductAssetKind = "block" | "section" | "template" | "layout";

/** Effective classification result (UNKNOWN = fail closed). */
export type ProductAssetClassification = "STANDARD" | "PREMIUM" | "UNKNOWN";

/** The capability that authorizes NEW selection/insertion/application. */
export type AssetRequiredCapability = ProductCapability;

/** Decision shape for an asset lookup. */
export interface AssetEntitlement {
  readonly classification: ProductAssetClassification;
  readonly requiredCapability: AssetRequiredCapability | null;
}

/* ============================================================================
 * 2. CLASSIFICATION → CAPABILITY MAPPING (canonical)
 * ========================================================================== */

const REQUIRED_CAPABILITY = {
  standardBlock: "standard_blocks",
  premiumBlock: "premium_blocks",
  standardSection: "standard_sections",
  premiumSection: "premium_sections",
  standardTemplate: "standard_templates",
  premiumTemplate: "premium_templates",
  standardLayout: "basic_layout_selection",
  premiumLayout: "advanced_layout",
} as const satisfies Record<string, ProductCapability>;

/* ============================================================================
 * 3. BLOCK MANIFEST (37 registered implemented block types)
 * ========================================================================== */

export const STANDARD_BLOCKS = [
  "hero",
  "heading",
  "text",
  "links",
  "featuredLink",
  "buttonGroup",
  "cta",
  "social",
  "video",
  "image",
  "gallery",
  "mediaCard",
  "portfolio",
  "document",
  "contact",
  "qr",
  "trust",
  "divider",
  "spacer",
  "services",
  "faq",
  "product",
  "map",
] as const;

export const PREMIUM_BLOCKS = [
  "stats",
  "testimonials",
  "pricing",
  "timeline",
  "featuredMedia",
  "floatingActions",
  "productGrid",
  "booking",
  "calendar",
  "events",
  "music",
  "carousel",
  "tabs",
  "bottomNav",
] as const;

/* ============================================================================
 * 4. LAYOUT MANIFEST (9 layouts, verified in constants/layouts.ts)
 * ========================================================================== */

export const STANDARD_LAYOUTS = ["centered", "compact", "profile-card"] as const;

export const PREMIUM_LAYOUTS = [
  "editorial",
  "bento",
  "split",
  "full-width",
  "portfolio",
  "executive",
] as const;

export type LayoutAssetId = (typeof STANDARD_LAYOUTS)[number] | (typeof PREMIUM_LAYOUTS)[number];

/* ============================================================================
 * 5. SECTION PRESET MANIFEST (29 section presets)
 * ========================================================================== */

export const STANDARD_SECTIONS = [
  "hero-medical-profile",
  "hero-professional-trust",
  "hero-executive-split",
  "hero-creator-editorial",
  "hero-creator-bento-intro",
  "services-bento",
  "services-cards",
  "services-editorial",
  "services-compact",
  "portfolio-bento",
  "portfolio-gallery",
  "portfolio-editorial",
  "product-spotlight",
  "contact-minimal",
  "contact-card",
  "contact-map",
] as const;

export const PREMIUM_SECTIONS = [
  "hero-creator-full-image",
  "booking-simple",
  "booking-split",
  "booking-premium-card",
  "reviews-cards",
  "reviews-featured",
  "reviews-trust-grid",
  "product-grid-premium",
  "product-bento-showcase",
  "media-featured-video",
  "media-music-spotlight",
  "media-bento",
  "contact-floating",
] as const;

export type SectionAssetId =
  | (typeof STANDARD_SECTIONS)[number]
  | (typeof PREMIUM_SECTIONS)[number];

/* ============================================================================
 * 6. TEMPLATE MANIFEST (42 templates: 12 base definitions + 30 recipes)
 * ========================================================================== */

export const STANDARD_TEMPLATES = [
  "creator-premium-001",
  "minimal-card-005",
  "ocean-studio-007",
  "warm-table-009",
  "medical-minimal",
  "beauty-studio",
  "portfolio-minimal",
] as const;

export const PREMIUM_TEMPLATES = [
  "executive-premium-002",
  "modern-bento-003",
  "editorial-journal-004",
  "luxury-noir-006",
  "graphite-folio-008",
  "cloud-corporate-010",
  "midnight-artist-011",
  "aurora-tech-012",
  "creator-premium",
  "creator-editorial",
  "creator-bento",
  "executive-premium",
  "professional-trust",
  "consultant-editorial",
  "medical-premium",
  "medical-booking",
  "barber-premium",
  "salon-booking",
  "restaurant-premium",
  "restaurant-visual",
  "cafe-minimal",
  "product-launch",
  "store-bento",
  "luxury-product",
  "fitness-coach",
  "personal-trainer",
  "fitness-program",
  "artist-premium",
  "music-release",
  "dj-events",
  "agent-premium",
  "property-showcase",
  "real-estate-bento",
  "portfolio-editorial",
  "portfolio-bento",
] as const;

export type TemplateAssetId =
  | (typeof STANDARD_TEMPLATES)[number]
  | (typeof PREMIUM_TEMPLATES)[number];

/* ============================================================================
 * 7. LOOKUP SETS (runtime fail-closed resolution)
 * ========================================================================== */

const STANDARD_BLOCK_SET: ReadonlySet<string> = new Set<string>(STANDARD_BLOCKS);
const PREMIUM_BLOCK_SET: ReadonlySet<string> = new Set<string>(PREMIUM_BLOCKS);
const STANDARD_LAYOUT_SET: ReadonlySet<string> = new Set<string>(STANDARD_LAYOUTS);
const PREMIUM_LAYOUT_SET: ReadonlySet<string> = new Set<string>(PREMIUM_LAYOUTS);
const STANDARD_SECTION_SET: ReadonlySet<string> = new Set<string>(STANDARD_SECTIONS);
const PREMIUM_SECTION_SET: ReadonlySet<string> = new Set<string>(PREMIUM_SECTIONS);
const STANDARD_TEMPLATE_SET: ReadonlySet<string> = new Set<string>(STANDARD_TEMPLATES);
const PREMIUM_TEMPLATE_SET: ReadonlySet<string> = new Set<string>(PREMIUM_TEMPLATES);

const UNKNOWN: AssetEntitlement = Object.freeze({
  classification: "UNKNOWN",
  requiredCapability: null,
});

function standardEntitlement(
  capability: AssetRequiredCapability,
): AssetEntitlement {
  return { classification: "STANDARD", requiredCapability: capability };
}

function premiumEntitlement(
  capability: AssetRequiredCapability,
): AssetEntitlement {
  return { classification: "PREMIUM", requiredCapability: capability };
}

/* ============================================================================
 * 8. PUBLIC LOOKUP HELPERS (pure, fail-closed)
 * ========================================================================== */

export function getBlockEntitlement(blockId: string): AssetEntitlement {
  if (STANDARD_BLOCK_SET.has(blockId)) {
    return standardEntitlement(REQUIRED_CAPABILITY.standardBlock);
  }
  if (PREMIUM_BLOCK_SET.has(blockId)) {
    return premiumEntitlement(REQUIRED_CAPABILITY.premiumBlock);
  }
  return UNKNOWN;
}

export function getSectionEntitlement(sectionId: string): AssetEntitlement {
  if (STANDARD_SECTION_SET.has(sectionId)) {
    return standardEntitlement(REQUIRED_CAPABILITY.standardSection);
  }
  if (PREMIUM_SECTION_SET.has(sectionId)) {
    return premiumEntitlement(REQUIRED_CAPABILITY.premiumSection);
  }
  return UNKNOWN;
}

export function getTemplateEntitlement(templateId: string): AssetEntitlement {
  if (STANDARD_TEMPLATE_SET.has(templateId)) {
    return standardEntitlement(REQUIRED_CAPABILITY.standardTemplate);
  }
  if (PREMIUM_TEMPLATE_SET.has(templateId)) {
    return premiumEntitlement(REQUIRED_CAPABILITY.premiumTemplate);
  }
  return UNKNOWN;
}

export function getLayoutEntitlement(layoutId: string): AssetEntitlement {
  if (STANDARD_LAYOUT_SET.has(layoutId)) {
    return standardEntitlement(REQUIRED_CAPABILITY.standardLayout);
  }
  if (PREMIUM_LAYOUT_SET.has(layoutId)) {
    return premiumEntitlement(REQUIRED_CAPABILITY.premiumLayout);
  }
  return UNKNOWN;
}

/** Generic resolver: (kind, assetId) → AssetEntitlement. */
export function resolveAssetEntitlement(
  kind: ProductAssetKind,
  assetId: string,
): AssetEntitlement {
  switch (kind) {
    case "block":
      return getBlockEntitlement(assetId);
    case "section":
      return getSectionEntitlement(assetId);
    case "template":
      return getTemplateEntitlement(assetId);
    case "layout":
      return getLayoutEntitlement(assetId);
  }
}


