import * as React from "react";

type LinkItem = { id: string; label: string; url: string; description?: string };
export type TemplateEudoraProps = { name?: string; profession?: string; description?: string; avatarUrl?: string; backgroundUrl?: string; logoUrl?: string; primaryColor?: string; secondaryColor?: string; links?: LinkItem[]; footerText?: string };
const Arrow = () => <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h12M11 5l5 5-5 5" /></svg>;
const defaults: LinkItem[] = [{ id: "facebook", label: "Facebook", url: "#" }, { id: "instagram", label: "Instagram", url: "#" }, { id: "email", label: "E-mail", url: "#" }, { id: "whatsapp", label: "Whatsapp", url: "#" }, { id: "location", label: "Localização", url: "#" }];
export default function TemplateEudora({ name = "Vanesa Alves", profession = "Consultora", description = "Escolhas que aproximam você do que deseja.", avatarUrl, backgroundUrl, logoUrl, primaryColor = "#f3b8bd", secondaryColor = "#7e4777", links = defaults, footerText = "Clique para interagir" }: TemplateEudoraProps) {
  const css = `.eudora{--pink:${primaryColor};--mauve:${secondaryColor};min-height:620px;background:linear-gradient(160deg,#a76a97,#c47e9a 57%,#59426e);color:#fff;font-family:Arial,sans-serif;padding:28px 20px 25px;position:relative;overflow:hidden}.eudora:before{content:"";position:absolute;width:115%;height:77%;left:-50%;top:-6%;border-radius:50%;background:rgba(234,168,190,.2);transform:rotate(24deg)}.eudora:after{content:"";position:absolute;width:98%;height:58%;right:-65%;bottom:-5%;border-radius:50%;background:rgba(35,19,56,.18);transform:rotate(-27deg)}.eudora *{box-sizing:border-box}.eudora-shell{position:relative;z-index:1;max-width:540px;margin:auto;text-align:center}.eudora-logo{height:105px;display:grid;place-items:center;overflow:hidden;margin-bottom:15px}.eudora-logo img{max-width:100%;height:100%;object-fit:contain}.eudora-logo:not(:has(img)){font-family:Georgia,serif;font-size:76px;letter-spacing:-.08em}.eudora h1{font-size:34px;line-height:.92;margin:0;font-weight:800;letter-spacing:.02em;text-transform:uppercase}.eudora-kicker{font-size:18px;letter-spacing:.33em;margin:22px 0 9px;color:#2b1b34;font-weight:bold;text-transform:uppercase}.eudora-desc{font-size:12px;line-height:1.45;margin:0 auto 22px;max-width:295px;color:rgba(255,255,255,.9)}.eudora-avatar{width:174px;height:174px;margin:0 auto 18px;border-radius:50%;overflow:hidden;background:var(--pink);border:5px solid var(--pink);box-shadow:0 0 0 4px var(--mauve)}.eudora-avatar img{width:100%;height:100%;object-fit:cover}.eudora-links{display:grid;grid-template-columns:1fr 1fr;gap:13px 18px;max-width:420px;margin:0 auto}.eudora-link{height:51px;display:flex;align-items:center;justify-content:center;gap:7px;color:#fff;text-decoration:none;background:linear-gradient(90deg,rgba(255,194,205,.34),rgba(255,255,255,.12));border:1px solid rgba(255,200,216,.85);border-radius:17px;box-shadow:inset -28px 0 rgba(255,255,255,.17);font-size:13px;font-weight:700}.eudora-link:hover{background:var(--pink);color:#452743}.eudora-link svg{width:14px;fill:none;stroke:currentColor;stroke-width:1.5}.eudora-main{grid-column:1/-1;max-width:270px;margin:auto}.eudora-footer{display:flex;justify-content:center;align-items:center;gap:9px;margin-top:39px;font-size:13px}.eudora-footer span{font-size:22px}@media(max-width:350px){.eudora{padding-left:12px;padding-right:12px}.eudora h1{font-size:29px}.eudora-links{gap:9px}.eudora-link{font-size:11px}}@media(min-width:650px){.eudora{padding:50px 30px}.eudora-avatar{width:210px;height:210px}.eudora h1{font-size:45px}.eudora-link{height:58px;font-size:15px}}
`;
  return <section className="eudora" style={backgroundUrl ? { backgroundImage: `linear-gradient(160deg,rgba(110,54,108,.45),rgba(196,126,154,.72)),url(${backgroundUrl})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><style>{css}</style><div className="eudora-shell"><div className="eudora-logo">{logoUrl ? <img src={logoUrl} alt="Logo" /> : "Eudora"}</div><div className="eudora-avatar">{avatarUrl && <img src={avatarUrl} alt={name} />}</div><p className="eudora-kicker">{profession}</p><h1>{name}</h1><p className="eudora-desc">{description}</p><nav className="eudora-links" aria-label="Redes y contacto"><>{links.slice(0, 5).map((link, i) => <a className={`eudora-link ${i === 0 ? "eudora-main" : ""}`} key={link.id} href={link.url}><span aria-hidden="true">{i === 0 ? "↗" : "◌"}</span>{link.label}<Arrow /></a>)}</></nav><footer className="eudora-footer"><span aria-hidden="true">♧</span>{footerText}</footer></div></section>;
}
