import {
  BathIcon,
  BriefcaseIcon,
  BrushIcon,
  BuildingIcon,
  CakeSliceIcon,
  CameraIcon,
  CoffeeIcon,
  FileTextIcon,
  Flower2Icon,
  GemIcon,
  HeartIcon,
  LeafIcon,
  type LucideIcon,
  PackageIcon,
  PaletteIcon,
  PawPrintIcon,
  PizzaIcon,
  ScaleIcon,
  ScissorsIcon,
  ShoppingBagIcon,
  SparklesIcon,
  StarIcon,
  StethoscopeIcon,
  UsersIcon,
  UtensilsCrossedIcon,
  WineIcon } from
'lucide-react';
import type { IconKey } from '../../types/cripqer';

/** Static icons supported by the editor's typography/icon set. */
export const serviceIcons: Record<IconKey, LucideIcon> = {
  paw: PawPrintIcon,
  scissors: ScissorsIcon,
  bath: BathIcon,
  bag: ShoppingBagIcon,
  stethoscope: StethoscopeIcon,
  sparkles: SparklesIcon,
  utensils: UtensilsCrossedIcon,
  pizza: PizzaIcon,
  wine: WineIcon,
  cake: CakeSliceIcon,
  coffee: CoffeeIcon,
  briefcase: BriefcaseIcon,
  scale: ScaleIcon,
  file: FileTextIcon,
  users: UsersIcon,
  heart: HeartIcon,
  gem: GemIcon,
  flower: Flower2Icon,
  camera: CameraIcon,
  brush: BrushIcon,
  palette: PaletteIcon,
  leaf: LeafIcon,
  package: PackageIcon,
  building: BuildingIcon,
  star: StarIcon
};