/**
 * Motor declarativo del candidato aislado. Todo el contenido visual, sus
 * overrides responsivos y las decoraciones viven en PageConfig: no hay modelos
 * distintos por dispositivo ni propiedades visuales ocultas en componentes.
 */
export type CandidateMode = "mobile" | "desktop";
export type CandidateTool = "select" | "text" | "font" | "color" | "format" | "effects" | "image" | "button" | "background" | "layers" | "advanced";
export type Breakpoint = "mobile" | "tablet" | "desktop";
export type BlockType = "banner" | "profile" | "heading" | "text" | "links" | "socials" | "image" | "video" | "cards" | "separator" | "spacer" | "gallery" | "services" | "reviews" | "products" | "booking" | "faq" | "contact" | "map" | "shape" | "ring" | "ornament" | "frame" | "particles" | "footer";
export type AddableContent = "title" | "text" | "link" | "image" | "video" | "cards" | "socials" | "separator" | "spacer" | "gallery" | "services" | "reviews" | "products" | "booking" | "faq" | "contact" | "map" | "shape" | "ring" | "ornament" | "frame" | "particles";
export type LinkVariant = "solid" | "glass" | "outline" | "soft" | "premium" | "minimal" | "neon" | "gradient" | "image";
export type LinkItem = { id: string; label: string; url: string; enabled: boolean; icon?: string | null; style?: { variant?: LinkVariant; color?: string; textColor?: string; borderColor?: string; radius?: number; shadow?: number; imageUrl?: string } };
export type SocialNetwork = "instagram" | "facebook" | "tiktok" | "x" | "linkedin" | "whatsapp" | "youtube" | "telegram" | "email" | "website";
export type SocialItem = { id: string; network: SocialNetwork; url: string; enabled: boolean };
export type ResponsiveOverride = { hidden?: boolean; columns?: number; gap?: number; fontSize?: number; align?: "left" | "center" | "right"; padding?: number; marginTop?: number; marginBottom?: number };
export type BlockVisualStyle = {
  composition: { marginTop: number; marginBottom: number; padding: number; gap: number; width: number; maxWidth: number; minHeight: number; align: "left" | "center" | "right"; verticalAlign: "top" | "middle" | "bottom"; columns: number; translateX: number; translateY: number; snap: boolean };
  border: { style: "none" | "solid" | "dashed" | "dotted" | "double"; width: number; color: string; opacity: number; radius: number };
  shadow: { preset: "none" | "soft" | "floating" | "deep" | "premium" | "glow"; x: number; y: number; blur: number; spread: number; color: string; opacity: number };
  glow: { preset: "none" | "white" | "gold" | "blue" | "pink" | "purple"; color: string; intensity: number; blur: number; spread: number };
  glass: { enabled: boolean; transparency: number; blur: number; tint: string; borderOpacity: number; highlight: number };
  gradient: { enabled: boolean; type: "linear" | "radial"; start: string; middle: string; end: string; angle: number; position: number };
  filters: { brightness: number; contrast: number; saturation: number; blur: number; grayscale: number; opacity: number };
  effectPreset: "none" | "inner-shadow" | "vignette" | "spotlight" | "light-leak" | "frosted" | "outer-glow" | "neon" | "gold-glow" | "chromatic" | "grain";
  blendMode: "normal" | "multiply" | "screen" | "overlay" | "soft-light";
  mask: "none" | "circle" | "rounded" | "arch" | "blob" | "organic" | "hexagon";
  motion: { preset: "none" | "fade" | "slide-up" | "slide-down" | "slide-left" | "slide-right" | "zoom" | "soft-bounce" | "blur-in" | "float" | "pulse" | "slow-rotate" | "glow-pulse" | "drift"; duration: number; delay: number; intensity: number; loop: boolean };
  responsive: Record<Breakpoint, ResponsiveOverride>;
};
export type PageBlock = { id: string; type: BlockType; order: number; enabled: boolean; locked?: boolean; name?: string; groupId?: string; props: Record<string, unknown> };
export type EditorCapabilities = { maxLinks: number; allowVideos: boolean; allowCards: boolean; allowSocials: boolean; allowGallery: boolean; allowAdvancedStyles: boolean; allowAdvancedLayouts: boolean; allowProducts: boolean; allowBooking: boolean; allowDecorations: boolean; allowParticles: boolean; allowAnimations: boolean; allowResponsive: boolean; allowPresets: boolean; allowImportExport: boolean; canRemoveCripqerBranding: boolean };
export type StylePreset = { id: string; name: string; category: "typography" | "button" | "card" | "image" | "effects" | "background"; style: Partial<BlockVisualStyle> };
export type PageConfig = { version: number; profile: "fixed" | "dynamic" | "premium"; capabilities: EditorCapabilities; branding: { showCripqerWatermark: boolean }; theme: { fontFamily: string; titleColor: string; fontSize: number; fontWeight: number; buttonColor: string; buttonRadius: number; buttonGap: number; buttonHeight: number; buttonPaddingX: number; buttonPaddingY: number; titleShadow: number }; background: { base: string; gradientEnd: string; gradient: boolean; angle: number; pattern: "none" | "dots" | "grid" | "lines" | "diagonal" | "noise" | "geometric" | "waves"; patternColor: string; patternOpacity: number; texture: "none" | "grain" | "paper" | "metallic"; light: "none" | "radial" | "spotlight" | "flare" | "ambient" }; blocks: PageBlock[]; presets: StylePreset[] };

export const NATURAL_TEMPLATE = { width: 390, height: 690 };
export const STORAGE_KEY = "cripqer.editor-candidate.v3";
export const capabilityProfiles: Record<PageConfig["profile"], EditorCapabilities> = {
  fixed: { maxLinks: 1, allowVideos: false, allowCards: false, allowSocials: true, allowGallery: false, allowAdvancedStyles: false, allowAdvancedLayouts: false, allowProducts: false, allowBooking: false, allowDecorations: false, allowParticles: false, allowAnimations: false, allowResponsive: false, allowPresets: false, allowImportExport: false, canRemoveCripqerBranding: false },
  dynamic: { maxLinks: 10, allowVideos: true, allowCards: true, allowSocials: true, allowGallery: true, allowAdvancedStyles: false, allowAdvancedLayouts: false, allowProducts: false, allowBooking: true, allowDecorations: false, allowParticles: false, allowAnimations: false, allowResponsive: false, allowPresets: false, allowImportExport: true, canRemoveCripqerBranding: false },
  premium: { maxLinks: 40, allowVideos: true, allowCards: true, allowSocials: true, allowGallery: true, allowAdvancedStyles: true, allowAdvancedLayouts: true, allowProducts: true, allowBooking: true, allowDecorations: true, allowParticles: true, allowAnimations: true, allowResponsive: true, allowPresets: true, allowImportExport: true, canRemoveCripqerBranding: true },
};

let sequence = 0;
export function stableId(prefix: string) { sequence += 1; return `${prefix}-${Date.now().toString(36)}-${sequence}`; }
export function defaultBlockStyle(): BlockVisualStyle { return { composition: { marginTop: 16, marginBottom: 0, padding: 0, gap: 8, width: 100, maxWidth: 100, minHeight: 0, align: "center", verticalAlign: "top", columns: 1, translateX: 0, translateY: 0, snap: true }, border: { style: "none", width: 0, color: "#c49a68", opacity: 100, radius: 12 }, shadow: { preset: "none", x: 0, y: 8, blur: 22, spread: 0, color: "#000000", opacity: 28 }, glow: { preset: "none", color: "#c49a68", intensity: 0, blur: 18, spread: 0 }, glass: { enabled: false, transparency: 14, blur: 10, tint: "#ffffff", borderOpacity: 25, highlight: 20 }, gradient: { enabled: false, type: "linear", start: "#c49a68", middle: "#9b6b42", end: "#171b24", angle: 135, position: 50 }, filters: { brightness: 100, contrast: 100, saturation: 100, blur: 0, grayscale: 0, opacity: 100 }, effectPreset: "none", blendMode: "normal", mask: "none", motion: { preset: "none", duration: 500, delay: 0, intensity: 1, loop: false }, responsive: { mobile: {}, tablet: {}, desktop: {} } }; }
export function getBlockStyle(block?: PageBlock): BlockVisualStyle { const base = defaultBlockStyle(); const raw = block?.props.style; const current = (raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {}) as Partial<BlockVisualStyle>; return { ...base, ...current, composition: { ...base.composition, ...current.composition }, border: { ...base.border, ...current.border }, shadow: { ...base.shadow, ...current.shadow }, glow: { ...base.glow, ...current.glow }, glass: { ...base.glass, ...current.glass }, gradient: { ...base.gradient, ...current.gradient }, filters: { ...base.filters, ...current.filters }, motion: { ...base.motion, ...current.motion }, responsive: { ...base.responsive, ...current.responsive, mobile: { ...base.responsive.mobile, ...current.responsive?.mobile }, tablet: { ...base.responsive.tablet, ...current.responsive?.tablet }, desktop: { ...base.responsive.desktop, ...current.responsive?.desktop } } }; }
export function resolveResponsiveStyle(block: PageBlock, breakpoint: Breakpoint) { const style = getBlockStyle(block); return { ...style, composition: { ...style.composition, ...style.responsive[breakpoint] }, hidden: Boolean(style.responsive[breakpoint]?.hidden) }; }

export const initialPageConfig: PageConfig = {
  version: 3, profile: "premium", capabilities: capabilityProfiles.premium, branding: { showCripqerWatermark: true },
  theme: { fontFamily: "Manrope", titleColor: "#f5f3ee", fontSize: 30, fontWeight: 800, buttonColor: "#c49a68", buttonRadius: 15, buttonGap: 12, buttonHeight: 46, buttonPaddingX: 16, buttonPaddingY: 10, titleShadow: 14 },
  background: { base: "#171b24", gradientEnd: "#2c1c17", gradient: true, angle: 145, pattern: "grid", patternColor: "#ffffff", patternOpacity: 5, texture: "grain", light: "ambient" }, presets: [],
  blocks: [
    { id: "banner", type: "banner", order: 0, enabled: true, locked: true, name: "Banner", props: { height: 126, imageOpacity: 100, overlayColor: "#11141c", overlayOpacity: 25, blend: "soft", blendStrength: 40, fusionMode: "soft", fusionDepth: 46, fusionStrength: 100, fit: "cover", positionX: 50, positionY: 50, radius: 0, style: defaultBlockStyle() } },
    { id: "profile", type: "profile", order: 1, enabled: true, name: "Perfil", props: { logo: "CRIPQER", logoUrl: "", logoWidth: 120, logoAlign: "center", logoOpacity: 100, logoFit: "contain", logoRadius: 0, initials: "AM", size: 72, shape: "circle", borderWidth: 0, borderColor: "#c49a68", shadow: 18, align: "center", verticalPosition: "transition", overlap: 36, style: defaultBlockStyle() } },
    { id: "heading", type: "heading", order: 2, enabled: true, name: "Título", props: { text: "Diseña tu presencia.", align: "center", italic: false, underline: false, strikethrough: false, letterSpacing: -0.8, lineHeight: 1.08, style: defaultBlockStyle() } },
    { id: "subtitle", type: "text", order: 3, enabled: true, name: "Subtítulo", props: { text: "Una página que viaja contigo.", align: "center", style: defaultBlockStyle() } },
    { id: "links", type: "links", order: 4, enabled: true, name: "Enlaces", props: { layout: 1, items: [{ id: "link-agenda", label: "Reservar una conversación", url: "https://cripqer.me/agenda", enabled: true, style: { variant: "solid" } }, { id: "link-work", label: "Explorar trabajos", url: "https://cripqer.me/trabajos", enabled: true, style: { variant: "solid" } }] satisfies LinkItem[], style: defaultBlockStyle() } },
    { id: "socials", type: "socials", order: 5, enabled: true, name: "Redes", props: { align: "center", gap: 10, size: 18, color: "#c9cbd0", socialStyle: "simple", items: [{ id: "social-instagram", network: "instagram", url: "https://instagram.com", enabled: true }, { id: "social-linkedin", network: "linkedin", url: "https://linkedin.com", enabled: true }, { id: "social-email", network: "email", url: "mailto:hola@cripqer.me", enabled: true }] satisfies SocialItem[], style: defaultBlockStyle() } },
    { id: "footer", type: "footer", order: 6, enabled: true, name: "Footer", props: { topText: "", bottomText: "cripqer.me", align: "center", fontFamily: "DM Mono", fontSize: 7, color: "rgba(255,255,255,.35)", opacity: 70, divider: false, preset: "minimal", style: defaultBlockStyle() } },
  ],
};

export function clonePageConfig(config: PageConfig): PageConfig { return JSON.parse(JSON.stringify(config)) as PageConfig; }
export function allBlocks(config: PageConfig) { return [...config.blocks].sort((a, b) => a.order - b.order); }
export function orderedBlocks(config: PageConfig) { return allBlocks(config).filter(block => block.enabled); }
export function getBlock(config: PageConfig, id: string) { return config.blocks.find(block => block.id === id); }
export function getLinks(block?: PageBlock) { return (block?.type === "links" ? block.props.items : []) as LinkItem[]; }
export function getSocials(block?: PageBlock) { return (block?.type === "socials" ? block.props.items : []) as SocialItem[]; }
export function getBlockLabel(block: PageBlock) { return block.name || ({ banner: "Banner", profile: "Perfil", heading: "Título", text: "Texto", links: "Enlaces", socials: "Redes", image: "Imagen", video: "Vídeo", cards: "Tarjetas", separator: "Separador", spacer: "Espaciador", gallery: "Galería", services: "Servicios", reviews: "Reseñas", products: "Productos", booking: "Reserva", faq: "Preguntas", contact: "Contacto", map: "Ubicación", shape: "Forma", ring: "Anillo", ornament: "Ornamento", frame: "Marco", particles: "Partículas", footer: "Footer" } as Record<BlockType, string>)[block.type]; }
export function isDecoration(block: PageBlock) { return ["shape", "ring", "ornament", "frame", "particles"].includes(block.type); }
export function toolsetForBlock(block?: PageBlock): CandidateTool[] { if (!block) return ["select", "background", "layers"]; if (isDecoration(block) || ["separator", "spacer"].includes(block.type)) return ["select", "color", "effects", "background", "layers"]; if (block.type === "socials") return ["select", "text", "color", "effects", "background", "layers"]; if (["banner", "profile", "image", "gallery"].includes(block.type)) return ["select", "image", "background", "color", "effects", "advanced", "layers"]; if (block.type === "links") return ["select", "button", "color", "format", "effects", "background", "advanced", "layers"]; return ["select", "text", "font", "color", "format", "effects", "background", "advanced", "layers"]; }
export function fitCanvas(availableWidth: number, availableHeight: number, padding = 24) { return Math.min(Math.max(0, availableWidth - padding * 2) / NATURAL_TEMPLATE.width, Math.max(0, availableHeight - padding * 2) / NATURAL_TEMPLATE.height, 1); }
export function reorder<T>(items: T[], from: number, to: number) { const next = [...items]; const [item] = next.splice(from, 1); if (item === undefined) return items; next.splice(Math.max(0, Math.min(next.length, to)), 0, item); return next; }
export function normalizeOrders(config: PageConfig): PageConfig { return { ...config, blocks: config.blocks.map((block, index) => ({ ...block, order: index })) }; }
export function updateBlock(config: PageConfig, blockId: string, patch: Partial<PageBlock>): PageConfig { return { ...config, blocks: config.blocks.map(block => block.id === blockId ? { ...block, ...patch, props: patch.props ? { ...block.props, ...patch.props } : block.props } : block) }; }
export function updateBlockStyle(config: PageConfig, blockId: string, patch: Partial<BlockVisualStyle>): PageConfig { const block = getBlock(config, blockId); if (!block) return config; const style = getBlockStyle(block); return updateBlock(config, blockId, { props: { style: { ...style, ...patch, composition: { ...style.composition, ...patch.composition }, border: { ...style.border, ...patch.border }, shadow: { ...style.shadow, ...patch.shadow }, glow: { ...style.glow, ...patch.glow }, glass: { ...style.glass, ...patch.glass }, gradient: { ...style.gradient, ...patch.gradient }, filters: { ...style.filters, ...patch.filters }, motion: { ...style.motion, ...patch.motion }, responsive: { ...style.responsive, ...patch.responsive } } } }); }
export function removeBlock(config: PageConfig, blockId: string): PageConfig { return normalizeOrders({ ...config, blocks: config.blocks.filter(block => block.id !== blockId) }); }
export function reorderBlock(config: PageConfig, from: number, to: number): PageConfig { return normalizeOrders({ ...config, blocks: reorder(allBlocks(config), from, to) }); }
export function bringBlockToFront(config: PageConfig, blockId: string) { const index = allBlocks(config).findIndex(block => block.id === blockId); return index < 0 ? config : reorderBlock(config, index, config.blocks.length - 1); }
export function sendBlockToBack(config: PageConfig, blockId: string) { const index = allBlocks(config).findIndex(block => block.id === blockId); return index < 0 ? config : reorderBlock(config, index, 0); }
export function setGroup(config: PageConfig, ids: string[], groupId?: string) { return { ...config, blocks: config.blocks.map(block => ids.includes(block.id) ? { ...block, groupId } : block) }; }
export function duplicateBlock(config: PageConfig, blockId: string) { const source = getBlock(config, blockId); if (!source) return { config, blockId: undefined as string | undefined }; const clone = clonePageConfig({ ...config, blocks: [source] }).blocks[0]; const id = stableId(source.type); const next: PageBlock = { ...clone, id, name: `${getBlockLabel(source)} copia`, order: config.blocks.length, props: { ...clone.props } }; ["links", "socials", "video", "cards", "gallery", "services", "products", "reviews", "faq"].includes(next.type) && (next.props.items = ((next.props.items ?? []) as Array<{ id: string }>).map(item => ({ ...item, id: stableId(next.type.slice(0, -1) || "item") }))); return { config: normalizeOrders({ ...config, blocks: [...config.blocks, next] }), blockId: id }; }

function baseProps(type: Exclude<AddableContent, "link">): Record<string, unknown> {
  const style = defaultBlockStyle();
  const defaults: Record<Exclude<AddableContent, "link">, Record<string, unknown>> = {
    title: { text: "Nuevo título", align: "center", letterSpacing: -0.5, lineHeight: 1.1, style }, text: { text: "Nuevo texto", align: "center", style }, image: { label: "Imagen", url: "", alt: "Imagen nueva", height: 150, fit: "cover", opacity: 100, radius: 14, positionX: 50, positionY: 50, style }, video: { layout: "full", aspectRatio: "16:9", radius: 14, items: [{ id: stableId("video"), title: "Vídeo 1", url: "" }], style }, cards: { layout: 1, items: [{ id: stableId("card"), title: "Nueva tarjeta", description: "Describe este contenido", cta: "Saber más", ctaUrl: "", imageUrl: "", objectPosition: "50% 50%" }], style }, socials: { align: "center", gap: 10, size: 18, color: "#c9cbd0", socialStyle: "simple", items: [], style }, separator: { dividerStyle: "solid", color: "#c49a68", width: 1, style }, spacer: { height: 24, style }, gallery: { layout: 2, gap: 8, radius: 12, aspectRatio: "1:1", items: [], style }, services: { layout: 1, items: [{ id: stableId("service"), title: "Nuevo servicio", description: "Explica qué ofreces", cta: "Consultar", url: "", imageUrl: "", icon: "sparkles" }], style }, reviews: { layout: "cards", featuredId: "", items: [], style }, products: { layout: 2, items: [{ id: stableId("product"), title: "Nuevo producto", description: "Describe este producto", price: "", cta: "Ver más", url: "", imageUrl: "" }], style }, booking: { title: "Reserva una sesión", description: "Elige un momento que te acomode.", cta: "Reservar", url: "", style }, faq: { layout: 1, items: [{ id: stableId("faq"), title: "Pregunta frecuente", description: "Respuesta clara para tu audiencia." }], style }, contact: { title: "Hablemos", description: "Escríbeme para colaborar.", email: "", phone: "", style }, map: { title: "Ubicación", address: "Agrega una dirección", style }, shape: { shape: "circle", color: "#c49a68", stroke: "#f5f3ee", opacity: 55, size: 86, rotation: 0, position: "top-right", style }, ring: { color: "#c49a68", thickness: 2, size: 108, partial: false, position: "bottom-left", style }, ornament: { preset: "gold-corner", position: "top-left", insetX: 14, insetY: 14, size: 52, thickness: 2, color: "#c49a68", opacity: 75, style }, frame: { preset: "double", inset: 12, thickness: 1, color: "#c49a68", opacity: 45, radius: 22, style }, particles: { preset: "soft-dots", quantity: 14, size: 3, opacity: 35, speed: 8, direction: "up", color: "#c49a68", randomness: 60, blur: 0, style },
  };
  return defaults[type];
}
function defaultBlock(type: Exclude<AddableContent, "link">): PageBlock { const id = stableId(type); return { id, type: type === "title" ? "heading" : type, order: 0, enabled: true, name: type === "title" ? "Título" : undefined, props: baseProps(type) }; }
export function addContent(config: PageConfig, content: AddableContent, afterBlockId?: string) { if (content === "link") { const linksBlock = config.blocks.find(block => block.type === "links"); if (!linksBlock || getLinks(linksBlock).length >= config.capabilities.maxLinks) return { config, blocked: true, blockId: linksBlock?.id, linkId: undefined as string | undefined }; const inheritedStyle = getLinks(linksBlock).find(link => link.enabled)?.style ?? { variant: "solid" }; const link: LinkItem = { id: stableId("link"), label: `Nuevo enlace ${getLinks(linksBlock).length + 1}`, url: "https://", enabled: true, style: { ...inheritedStyle } }; return { config: updateBlock(config, linksBlock.id, { props: { items: [...getLinks(linksBlock), link] } }), blocked: false, blockId: linksBlock.id, linkId: link.id }; } const capability: Partial<Record<AddableContent, keyof EditorCapabilities>> = { video: "allowVideos", cards: "allowCards", socials: "allowSocials", gallery: "allowGallery", products: "allowProducts", booking: "allowBooking", shape: "allowDecorations", ring: "allowDecorations", ornament: "allowDecorations", frame: "allowDecorations", particles: "allowParticles" }; if (capability[content] && !config.capabilities[capability[content]!]) return { config, blocked: true, blockId: undefined as string | undefined, linkId: undefined as string | undefined }; const block = defaultBlock(content); const ordered = allBlocks(config); const selectedIndex = afterBlockId ? ordered.findIndex(item => item.id === afterBlockId) : -1; const footerIndex = ordered.findIndex(item => item.type === "footer"); const insertionIndex = selectedIndex >= 0 && ordered[selectedIndex]?.type !== "footer" ? selectedIndex + 1 : footerIndex >= 0 ? footerIndex : ordered.length; const blocks = [...ordered]; blocks.splice(insertionIndex, 0, block); return { config: normalizeOrders({ ...config, blocks }), blocked: false, blockId: block.id, linkId: undefined as string | undefined }; }
export function updateLink(config: PageConfig, blockId: string, linkId: string, patch: Partial<LinkItem>) { const block = getBlock(config, blockId); return !block || block.type !== "links" ? config : updateBlock(config, blockId, { props: { items: getLinks(block).map(link => link.id === linkId ? { ...link, ...patch, style: patch.style ? { ...link.style, ...patch.style } : link.style } : link) } }); }
export function duplicateLink(config: PageConfig, blockId: string, linkId: string) { const block = getBlock(config, blockId); if (!block || block.type !== "links" || getLinks(block).length >= config.capabilities.maxLinks) return { config, linkId: undefined as string | undefined }; const source = getLinks(block).find(link => link.id === linkId); if (!source) return { config, linkId: undefined as string | undefined }; const clone = { ...source, id: stableId("link"), label: `${source.label} (copia)` }; return { config: updateBlock(config, blockId, { props: { items: [...getLinks(block), clone] } }), linkId: clone.id }; }
export function removeLink(config: PageConfig, blockId: string, linkId: string) { const block = getBlock(config, blockId); return !block || block.type !== "links" ? config : updateBlock(config, blockId, { props: { items: getLinks(block).filter(link => link.id !== linkId) } }); }
export function reorderLink(config: PageConfig, blockId: string, from: number, to: number) { const block = getBlock(config, blockId); return !block || block.type !== "links" ? config : updateBlock(config, blockId, { props: { items: reorder(getLinks(block), from, to) } }); }
export function switchProfile(config: PageConfig, profile: PageConfig["profile"]): PageConfig { return { ...config, profile, capabilities: capabilityProfiles[profile] }; }
export function saveStylePreset(config: PageConfig, name: string, category: StylePreset["category"], block: PageBlock): PageConfig { const preset: StylePreset = { id: stableId("preset"), name, category, style: getBlockStyle(block) }; return { ...config, presets: [...config.presets, preset] }; }
export function applyStylePreset(config: PageConfig, blockId: string, presetId: string) { const preset = config.presets.find(item => item.id === presetId); return preset ? updateBlockStyle(config, blockId, preset.style) : config; }
export function getPublishIssues(config: PageConfig) { const issues: string[] = []; const links = config.blocks.find(block => block.type === "links"); if (links && getLinks(links).filter(link => link.enabled).length > config.capabilities.maxLinks) issues.push(`El perfil ${config.profile} admite hasta ${config.capabilities.maxLinks} enlace(s).`); const gated: Array<[BlockType, keyof EditorCapabilities]> = [["video", "allowVideos"], ["cards", "allowCards"], ["socials", "allowSocials"], ["gallery", "allowGallery"], ["products", "allowProducts"], ["booking", "allowBooking"], ["shape", "allowDecorations"], ["ring", "allowDecorations"], ["ornament", "allowDecorations"], ["frame", "allowDecorations"], ["particles", "allowParticles"]]; gated.forEach(([type, capability]) => { if (config.blocks.some(block => block.type === type && block.enabled) && !config.capabilities[capability]) issues.push(`${getBlockLabel({ id: type, type, order: 0, enabled: true, props: {} })} no está disponible en el perfil ${config.profile}.`); }); return issues; }
export function hydratePageConfig(input: PageConfig): PageConfig { const config = clonePageConfig(input); const sourceVersion = Number(config.version ?? 0); const migrated: PageConfig = { ...initialPageConfig, ...config, version: 5, capabilities: { ...capabilityProfiles[config.profile ?? "premium"], ...config.capabilities }, branding: { ...initialPageConfig.branding, ...config.branding }, theme: { ...initialPageConfig.theme, ...config.theme }, background: { ...initialPageConfig.background, ...config.background }, presets: config.presets ?? [], blocks: (config.blocks ?? []).map(block => { const props = { ...block.props }; if (block.type === "profile" && sourceVersion < 5 && props.verticalPosition === "body") { props.verticalPosition = "transition"; props.overlap = Number(props.overlap ?? 36); } if (block.type === "footer") { props.topText = String(props.topText ?? ""); props.bottomText = String(props.bottomText ?? props.text ?? ""); } if (block.type === "video" && !(props.items as Array<{ id: string }> | undefined)?.length) props.items = [{ id: stableId("video"), title: String(props.title ?? "Vídeo 1"), url: String(props.url ?? "") }]; if (typeof props.style !== "object" || Array.isArray(props.style)) { if (block.type === "socials" && typeof props.style === "string") props.socialStyle = props.style; if (block.type === "separator" && typeof props.style === "string") props.dividerStyle = props.style; props.style = defaultBlockStyle(); } return { ...block, name: block.name ?? getBlockLabel({ ...block, props }), props }; }) }; return normalizeOrders({ ...migrated, blocks: allBlocks(migrated) }); }
