/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliasRouteImport } from './routes/$alias'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EncryptedDocumentsRouteImport } from './routes/encrypted-documents'
import { Route as EngineLabRouteImport } from './routes/engine-lab'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding-preview'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TemplateLabRouteImport } from './routes/template-lab'
import { Route as DShortUrlRouteImport } from './routes/d.$shortUrl'
import { Route as InternalPowerEditorRouteImport } from './routes/internal.power-editor'
import { Route as PPublicIdRouteImport } from './routes/p.$publicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasRoute = AliasRouteImport.update({
  id: '/$alias',
  path: '/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptedDocumentsRoute = EncryptedDocumentsRouteImport.update({
  id: '/encrypted-documents',
  path: '/encrypted-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineLabRoute = EngineLabRouteImport.update({
  id: '/engine-lab',
  path: '/engine-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/onboarding-preview',
  path: '/onboarding-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateLabRoute = TemplateLabRouteImport.update({
  id: '/template-lab',
  path: '/template-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DShortUrlRoute = DShortUrlRouteImport.update({
  id: '/d/$shortUrl',
  path: '/d/$shortUrl',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPowerEditorRoute = InternalPowerEditorRouteImport.update({
  id: '/internal/power-editor',
  path: '/internal/power-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PPublicIdRoute = PPublicIdRouteImport.update({
  id: '/p/$publicId',
  path: '/p/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/engine-lab': typeof EngineLabRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/profile': typeof ProfileRoute
  '/template-lab': typeof TemplateLabRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/internal/power-editor': typeof InternalPowerEditorRoute
  '/p/$publicId': typeof PPublicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/engine-lab': typeof EngineLabRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/profile': typeof ProfileRoute
  '/template-lab': typeof TemplateLabRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/internal/power-editor': typeof InternalPowerEditorRoute
  '/p/$publicId': typeof PPublicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRoute
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/engine-lab': typeof EngineLabRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/profile': typeof ProfileRoute
  '/template-lab': typeof TemplateLabRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/internal/power-editor': typeof InternalPowerEditorRoute
  '/p/$publicId': typeof PPublicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$alias'
    | '/admin'
    | '/editor'
    | '/encrypted-documents'
    | '/engine-lab'
    | '/onboarding-preview'
    | '/profile'
    | '/template-lab'
    | '/d/$shortUrl'
    | '/internal/power-editor'
    | '/p/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$alias'
    | '/admin'
    | '/editor'
    | '/encrypted-documents'
    | '/engine-lab'
    | '/onboarding-preview'
    | '/profile'
    | '/template-lab'
    | '/d/$shortUrl'
    | '/internal/power-editor'
    | '/p/$publicId'
  id:
    | '__root__'
    | '/'
    | '/$alias'
    | '/admin'
    | '/editor'
    | '/encrypted-documents'
    | '/engine-lab'
    | '/onboarding-preview'
    | '/profile'
    | '/template-lab'
    | '/d/$shortUrl'
    | '/internal/power-editor'
    | '/p/$publicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliasRoute: typeof AliasRoute
  AdminRoute: typeof AdminRoute
  EditorRoute: typeof EditorRoute
  EncryptedDocumentsRoute: typeof EncryptedDocumentsRoute
  EngineLabRoute: typeof EngineLabRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  ProfileRoute: typeof ProfileRoute
  TemplateLabRoute: typeof TemplateLabRoute
  DShortUrlRoute: typeof DShortUrlRoute
  InternalPowerEditorRoute: typeof InternalPowerEditorRoute
  PPublicIdRoute: typeof PPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$alias': {
      id: '/$alias'
      path: '/$alias'
      fullPath: '/$alias'
      preLoaderRoute: typeof AliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypted-documents': {
      id: '/encrypted-documents'
      path: '/encrypted-documents'
      fullPath: '/encrypted-documents'
      preLoaderRoute: typeof EncryptedDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-lab': {
      id: '/engine-lab'
      path: '/engine-lab'
      fullPath: '/engine-lab'
      preLoaderRoute: typeof EngineLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-preview': {
      id: '/onboarding-preview'
      path: '/onboarding-preview'
      fullPath: '/onboarding-preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-lab': {
      id: '/template-lab'
      path: '/template-lab'
      fullPath: '/template-lab'
      preLoaderRoute: typeof TemplateLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$shortUrl': {
      id: '/d/$shortUrl'
      path: '/d/$shortUrl'
      fullPath: '/d/$shortUrl'
      preLoaderRoute: typeof DShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/power-editor': {
      id: '/internal/power-editor'
      path: '/internal/power-editor'
      fullPath: '/internal/power-editor'
      preLoaderRoute: typeof InternalPowerEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$publicId': {
      id: '/p/$publicId'
      path: '/p/$publicId'
      fullPath: '/p/$publicId'
      preLoaderRoute: typeof PPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliasRoute: AliasRoute,
  AdminRoute: AdminRoute,
  EditorRoute: EditorRoute,
  EncryptedDocumentsRoute: EncryptedDocumentsRoute,
  EngineLabRoute: EngineLabRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  ProfileRoute: ProfileRoute,
  TemplateLabRoute: TemplateLabRoute,
  DShortUrlRoute: DShortUrlRoute,
  InternalPowerEditorRoute: InternalPowerEditorRoute,
  PPublicIdRoute: PPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
