/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliasRouteImport } from './routes/$alias'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EncryptedDocumentsRouteImport } from './routes/encrypted-documents'
import { Route as PowerEditorPreviewRouteImport } from './routes/power-editor-preview'
import { Route as PowerEditorPreviewMobileRouteImport } from './routes/power-editor-preview-mobile'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TemplateBankRouteImport } from './routes/template-bank'
import { Route as TemplateBuilderRouteImport } from './routes/template-builder'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTemplateStudioRouteImport } from './routes/admin/template-studio'
import { Route as DShortUrlRouteImport } from './routes/d.$shortUrl'
import { Route as PPublicIdRouteImport } from './routes/p.$publicId'
import { Route as InternalPowerEditorDraftProjectIdRouteImport } from './routes/internal/power-editor-draft/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasRoute = AliasRouteImport.update({
  id: '/$alias',
  path: '/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptedDocumentsRoute = EncryptedDocumentsRouteImport.update({
  id: '/encrypted-documents',
  path: '/encrypted-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerEditorPreviewRoute = PowerEditorPreviewRouteImport.update({
  id: '/power-editor-preview',
  path: '/power-editor-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerEditorPreviewMobileRoute =
  PowerEditorPreviewMobileRouteImport.update({
    id: '/power-editor-preview-mobile',
    path: '/power-editor-preview-mobile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateBankRoute = TemplateBankRouteImport.update({
  id: '/template-bank',
  path: '/template-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateBuilderRoute = TemplateBuilderRouteImport.update({
  id: '/template-builder',
  path: '/template-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateStudioRoute = AdminTemplateStudioRouteImport.update({
  id: '/template-studio',
  path: '/template-studio',
  getParentRoute: () => AdminRoute,
} as any)
const DShortUrlRoute = DShortUrlRouteImport.update({
  id: '/d/$shortUrl',
  path: '/d/$shortUrl',
  getParentRoute: () => rootRouteImport,
} as any)
const PPublicIdRoute = PPublicIdRouteImport.update({
  id: '/p/$publicId',
  path: '/p/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPowerEditorDraftProjectIdRoute =
  InternalPowerEditorDraftProjectIdRouteImport.update({
    id: '/internal/power-editor-draft/$projectId',
    path: '/internal/power-editor-draft/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRouteWithChildren
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/power-editor-preview': typeof PowerEditorPreviewRoute
  '/power-editor-preview-mobile': typeof PowerEditorPreviewMobileRoute
  '/profile': typeof ProfileRoute
  '/template-bank': typeof TemplateBankRoute
  '/template-builder': typeof TemplateBuilderRoute
  '/admin/template-studio': typeof AdminTemplateStudioRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/internal/power-editor-draft/$projectId': typeof InternalPowerEditorDraftProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/power-editor-preview': typeof PowerEditorPreviewRoute
  '/power-editor-preview-mobile': typeof PowerEditorPreviewMobileRoute
  '/profile': typeof ProfileRoute
  '/template-bank': typeof TemplateBankRoute
  '/template-builder': typeof TemplateBuilderRoute
  '/admin/template-studio': typeof AdminTemplateStudioRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/admin': typeof AdminIndexRoute
  '/internal/power-editor-draft/$projectId': typeof InternalPowerEditorDraftProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/admin': typeof AdminRouteWithChildren
  '/editor': typeof EditorRoute
  '/encrypted-documents': typeof EncryptedDocumentsRoute
  '/power-editor-preview': typeof PowerEditorPreviewRoute
  '/power-editor-preview-mobile': typeof PowerEditorPreviewMobileRoute
  '/profile': typeof ProfileRoute
  '/template-bank': typeof TemplateBankRoute
  '/template-builder': typeof TemplateBuilderRoute
  '/admin/template-studio': typeof AdminTemplateStudioRoute
  '/d/$shortUrl': typeof DShortUrlRoute
  '/p/$publicId': typeof PPublicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/internal/power-editor-draft/$projectId': typeof InternalPowerEditorDraftProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$alias'
    | '/admin'
    | '/editor'
    | '/encrypted-documents'
    | '/power-editor-preview'
    | '/power-editor-preview-mobile'
    | '/profile'
    | '/template-bank'
    | '/template-builder'
    | '/admin/template-studio'
    | '/d/$shortUrl'
    | '/p/$publicId'
    | '/admin/'
    | '/internal/power-editor-draft/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$alias'
    | '/editor'
    | '/encrypted-documents'
    | '/power-editor-preview'
    | '/power-editor-preview-mobile'
    | '/profile'
    | '/template-bank'
    | '/template-builder'
    | '/admin/template-studio'
    | '/d/$shortUrl'
    | '/p/$publicId'
    | '/admin'
    | '/internal/power-editor-draft/$projectId'
  id:
    | '__root__'
    | '/'
    | '/$alias'
    | '/admin'
    | '/editor'
    | '/encrypted-documents'
    | '/power-editor-preview'
    | '/power-editor-preview-mobile'
    | '/profile'
    | '/template-bank'
    | '/template-builder'
    | '/admin/template-studio'
    | '/d/$shortUrl'
    | '/p/$publicId'
    | '/admin/'
    | '/internal/power-editor-draft/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliasRoute: typeof AliasRoute
  AdminRoute: typeof AdminRouteWithChildren
  EditorRoute: typeof EditorRoute
  EncryptedDocumentsRoute: typeof EncryptedDocumentsRoute
  PowerEditorPreviewRoute: typeof PowerEditorPreviewRoute
  PowerEditorPreviewMobileRoute: typeof PowerEditorPreviewMobileRoute
  ProfileRoute: typeof ProfileRoute
  TemplateBankRoute: typeof TemplateBankRoute
  TemplateBuilderRoute: typeof TemplateBuilderRoute
  DShortUrlRoute: typeof DShortUrlRoute
  PPublicIdRoute: typeof PPublicIdRoute
  InternalPowerEditorDraftProjectIdRoute: typeof InternalPowerEditorDraftProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$alias': {
      id: '/$alias'
      path: '/$alias'
      fullPath: '/$alias'
      preLoaderRoute: typeof AliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypted-documents': {
      id: '/encrypted-documents'
      path: '/encrypted-documents'
      fullPath: '/encrypted-documents'
      preLoaderRoute: typeof EncryptedDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-editor-preview': {
      id: '/power-editor-preview'
      path: '/power-editor-preview'
      fullPath: '/power-editor-preview'
      preLoaderRoute: typeof PowerEditorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-editor-preview-mobile': {
      id: '/power-editor-preview-mobile'
      path: '/power-editor-preview-mobile'
      fullPath: '/power-editor-preview-mobile'
      preLoaderRoute: typeof PowerEditorPreviewMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-bank': {
      id: '/template-bank'
      path: '/template-bank'
      fullPath: '/template-bank'
      preLoaderRoute: typeof TemplateBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-builder': {
      id: '/template-builder'
      path: '/template-builder'
      fullPath: '/template-builder'
      preLoaderRoute: typeof TemplateBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template-studio': {
      id: '/admin/template-studio'
      path: '/template-studio'
      fullPath: '/admin/template-studio'
      preLoaderRoute: typeof AdminTemplateStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/d/$shortUrl': {
      id: '/d/$shortUrl'
      path: '/d/$shortUrl'
      fullPath: '/d/$shortUrl'
      preLoaderRoute: typeof DShortUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$publicId': {
      id: '/p/$publicId'
      path: '/p/$publicId'
      fullPath: '/p/$publicId'
      preLoaderRoute: typeof PPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/power-editor-draft/$projectId': {
      id: '/internal/power-editor-draft/$projectId'
      path: '/internal/power-editor-draft/$projectId'
      fullPath: '/internal/power-editor-draft/$projectId'
      preLoaderRoute: typeof InternalPowerEditorDraftProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminTemplateStudioRoute: typeof AdminTemplateStudioRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTemplateStudioRoute: AdminTemplateStudioRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliasRoute: AliasRoute,
  AdminRoute: AdminRouteWithChildren,
  EditorRoute: EditorRoute,
  EncryptedDocumentsRoute: EncryptedDocumentsRoute,
  PowerEditorPreviewRoute: PowerEditorPreviewRoute,
  PowerEditorPreviewMobileRoute: PowerEditorPreviewMobileRoute,
  ProfileRoute: ProfileRoute,
  TemplateBankRoute: TemplateBankRoute,
  TemplateBuilderRoute: TemplateBuilderRoute,
  DShortUrlRoute: DShortUrlRoute,
  PPublicIdRoute: PPublicIdRoute,
  InternalPowerEditorDraftProjectIdRoute:
    InternalPowerEditorDraftProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
